# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
# GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "weekly"
# Go modules in main branch
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  ## group all dependencies with a k8s.io prefix into a single PR.
  groups:
    kubernetes:
      patterns: [ "k8s.io/*" ]
